name: CI/CD da aplicação

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building application"
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installing dependencies
        run: |
          python -m pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests"
          
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installing dependencies
        run: |
          python -m pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Running pytest
        run: |
          pytest

  test_coverage:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Running test coverage report"

  deployment_app: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying application"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar .env
        run: |
          echo "FLASK_DEBUG=${{ secrets.FLASK_DEBUG }}" >> .env
          echo "FRANKFURTER_BASE_URL=${{ secrets.FRANKFURTER_BASE_URL }}" >> .env
          echo "REQUEST_TIMEOUT=${{ secrets.REQUEST_TIMEOUT }}" >> .env

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up --service $RAILWAY_SERVICE_ID --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}

  notification:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Notifying user on email"

